@base_url=http://localhost:8081

# @name auth
POST {{base_url}}/tokenz
Content-Type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

###

POST {{base_url}}/todos
Authorization: Bearer {{auth.token}}
Content-Type: application/json

{
  "text": "test 5"
}
